(defpackage :queue-test
  (:use :cl :lisp-unit2))
(in-package :queue-test)

(defun perf-test ()
  (declare (optimize (speed 3) (safety 0)))
  (let ((stopped? t))
    (declare (type boolean stopped?))
    (let ((thr (bt:make-thread (lambda ()
                                 (do ((queue (sb-concurrency:make-mailbox)))
                                     ((not stopped?)
                                      (do ((runs 0 (1+ runs)))
                                          (stopped? runs)
                                        (declare (type fixnum runs))
                                        (sb-concurrency:send-message queue 1)
                                        (sb-concurrency:receive-message queue))))))))
      (sleep 0.001)
      (setf stopped? nil)
      (time (sleep 1))
      (setf stopped? t)
      (bt:join-thread thr))))
